### ISSUE TITLE
Licences - Images

### ISSUE THREAD

**Issue by trosendal** [SVA-SE/AHSO#11]
Hi,

What are the licences on the images:

`/docs/img/Logo2.png` 

`/docs/img/smart solutions.png`

?

**Comment by FlavieVial** [comment]
I have bought these images on 123rf website so I guess they are licenced under my name. Should they have been bought under SVA's name?

**Comment by trosendal** [comment]
Good question. I'm not sure how it works if you have purchased the rights to use an image.

**Comment by nandadorea** [comment]
I have read a little on the website, and these images are licensed to Flavie to use and reproduce freely, although they cannot be used as part of a company logo, and are some restrictions once things start getting into articles and a large number of distributions. We may be safer sticking to logos/figures we produce ourselves. I will ask Mia how it went with ordering the Naveda logo.
